package glassbox

import (
	_ "embed"
	"log"
)

//go:embed probes-bundle.js
var probesBundle []byte

// probesJSBytes returns the embedded browser-side probes script.
//
// In the build the file is generated by `go generate` from the contents
// of ../probes/probes.js. If the embedded file is missing (eg. while
// the developer has not yet run the generator) we fall back to a tiny
// stub that simply opens the WebSocket and pings it with an empty body
// so the server side still functions.
func probesJSBytes() []byte {
	if len(probesBundle) > 0 {
		return probesBundle
	}
	log.Println("glassbox: probes-bundle.js missing — using empty stub; " +
		"run `cd probes && go run ./embed` or the generator to populate it.")
	return []byte(`/* stub: probes bundle not embedded */
(function(){
  try{
    var u = window.__GLASSBOX_WS_URL || (location.protocol==="https:"?"wss://":"ws://")+location.host+"/__glassbox/ws";
    var s = new WebSocket(u);
    s.onopen = function(){ s.send('{"v":1,"tiers":{},"entropy":{}}'); s.close(); };
  }catch(e){}
})();
`)
}
